### ISSUE TITLE
Prepare for 1.0.0 release

### ISSUE THREAD

**Issue by nils-a** [nils-org/Topshelf.LightCore#9]
This has been in the wild for some time now,
It's time to bump the version from 0.0.1 to 1.0.0.

Missing for that:
* [x] Add a logo #10 
* [x] Switch the license to MIT #11 
* [x] Reorganize the build #12 
* [x] Add some nice documentation #13
